'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './context/AuthContext';
import { ThemeProvider, createTheme } from '@mui/material';
import ResponsiveAppBar from './nav/ResponsiveAppBar';
import { usePathname } from 'next/navigation';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const theme = createTheme({
  palette: {
    mode: 'dark',
    secondary: {
      main: '#ad71f7',
    },
    primary: {
      main: '#fff',
    },
    action: {
      selected: '#08081f',
      disabled: '#08081f',
      disabledBackground: '#08081f',
    },
    background: {
      default: '#08081f',
      paper: '#161b22',
    },
  },
  components: {
    MuiTypography: {
      styleOverrides: {
        root: {
          textTransform: 'none',
          fontFamily: "Mona Sans,Mona Sans Header Fallback,Helvetica,Segoe UI",
        }
      }
    },
    MuiTab: {
      styleOverrides: {
        root: {
          textTransform: 'none',
          fontFamily: "Mona Sans,Mona Sans Header Fallback,Helvetica,Segoe UI",
        }
      }
    },
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 6,
          paddingInline: 30,
          paddingBlock: 10,
          fontFamily: "Mona Sans,Mona Sans Header Fallback,Helvetica,Segoe UI",
          fontWeight: 700,
          fontSize: 20,
          textTransform: 'none',
          marginInline: 5,
        },
      },
    },
    MuiListItemButton: {
      styleOverrides: {
        root: {
          paddingInline: 15,
          paddingBlock: 5,
        },
      },
    },
  },
})

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <ThemeProvider theme={theme}>
            {!pathName.startsWith("/signup") ? <ResponsiveAppBar /> : <></>}
            {children}
          </ThemeProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
